import schemaJson from "./schema.json" with { type: "json" };
import type { Schema } from "./types";

// Generated by `pnpm extract-schema` — do not edit by hand.
export const SCHEMA = schemaJson as unknown as Schema;
