// Snapshot bookmarklet source. Captures a page's live (post-JS) DOM, inlines the
// CSS properties the converter reads, strips scripts, and downloads/copies a
// self-contained .html for the Woofigma plugin.
//
// SNAPSHOT_STYLE_PROPS must stay in sync with the properties the converter reads
// in packages/dom-to-figma/src/converter. A guard test
// (snapshot-whitelist.test.ts) fails the build if the converter starts reading a
// property missing here.
export const SNAPSHOT_STYLE_PROPS = [
  "color",
  "font-family",
  "font-size",
  "font-style",
  "font-weight",
  "line-height",
  "letter-spacing",
  "word-spacing",
  "text-align",
  "text-decoration-line",
  "text-transform",
  "white-space",
  "background",
  "background-color",
  "background-image",
  "background-clip",
  "opacity",
  "display",
  "position",
  "overflow",
  "overflow-x",
  "overflow-y",
  "box-shadow",
  "filter",
  "backdrop-filter",
  "clip",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "border-width",
  "border-color",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "fill",
  "fill-opacity",
  "fill-rule",
  "stroke",
  "stroke-width",
  "stroke-opacity",
  "stroke-dasharray",
  "stroke-linecap",
  "stroke-linejoin",
  "clip-rule",
];
